name: Bug Report
description: Use this template to report a bug in the pipeline
title: "[BUG] "
labels: ["type/bug", "status/in-progress"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        **Describe the bug**
        A clear and concise description of what the bug is.

  - type: input
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: List the steps to reproduce the behavior
      placeholder: "1. Go to ... 2. Click on ... 3. See error"
      required: true

  - type: input
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What you expected to happen
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here
