name: Chore
description: Tasks that are not directly a bug or feature (refactoring, maintenance, etc.)
title: "[CHORE] "
labels: ["status/in-progress"]
assignees: []

body:
  - type: input
    id: task
    attributes:
      label: Task description
      description: Describe the maintenance or chore task
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context related to the task
